apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    app: cart
    demo: deployment
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
      demo: deployment
      env: dev
  template:
    metadata:
      labels:
        app: cart
        demo: deployment
        env: dev
    spec:
      containers:
      - name: cart
        image: praveen538/cart:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    app: cart
    demo: deployment
    env: dev 
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080 #container port
