apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST=: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    app: shipping
    demo: deployment
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
      demo: deployment
      env: dev
  template:
    metadata:
      labels:
        app: shipping
        demo: deployment
        env: dev
    spec:
      containers:
      - name: shipping
        image: praveen538/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    app: shipping
    demo: deployment
    env: dev 
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080 #container port
