apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    demo: deployment
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      demo: deployment
      env: dev
  template:
    metadata:
      labels:
        app: mongodb
        demo: deployment
        env: dev
    spec:
      containers:
      - name: mongodb
        image: praveen538/mongo:v1
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    demo: deployment
    env: dev 
  ports:
  - protocol: TCP
    port: 27017 #service port
    targetPort: 27017 #container port
