apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
---
apiVersion: v1
kind : Secret
metadata:
  name: mysql
  namespace: roboshop
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ==" #base64 encoded value
  MYSQL_PASSWORD: "Um9ib1Nob3BAMQ==" #base64 encoded value
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    demo: deployment
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      demo: deployment
      env: dev
  template:
    metadata:
      labels:
        app: mysql
        demo: deployment
        env: dev
    spec:
      containers:
      - name: mysql
        image: praveen538/mysql:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mysql
        - secretRef:
            name: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    app: mysql
    demo: deployment
    env: dev 
  ports:
  - protocol: TCP
    port: 3306 #service port
    targetPort: 3306 #container port
