apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboshop
  namespace: roboshop
  labels:
    app: catalogue
    demo: deployment
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      demo: deployment
      env: dev
  template:
    metadata:
      labels:
        app: catalogue
        demo: deployment
        env: dev
    spec:
      containers:
      - name: catalogue
        image: praveen538/mongo:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    app: catalogue
    demo: deployment
    env: dev 
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080 #container port
