apiVersion: v1
kind: ConfigMap
metadata:
  name: web
  namespace: roboshop
data:
  nginx.conf: |
    user www-data;
    worker_processes 4;
    pid /var/run/nginx.pid;

    events {
      worker_connections 768;
      # multi_accept on;
    }

    http {
      ##
      # Basic Settings
      ##
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 2048;
      large_client_header_buffers 6 32k;
      client_max_body_size 100m;

      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      ##
      # Logging Settings
      ##
      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log debug;

      ##
      # Gzip Settings
      ##
      gzip on;
      gzip_disable "msie6";

      ##
      # Virtual Host Configs
      ##
      include /etc/nginx/conf.d/*.conf;
      include /etc/nginx/sites-enabled/*;

      server {
        listen 80;
        server_name localhost;

        proxy_http_version 1.1;

        location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
          ssi on;
        }

        location /images/ {
          expires 5s;
          root /usr/share/nginx/html;
          try_files $uri /images/placeholder.png;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
          root /usr/share/nginx/html;
        }

        location /api/catalogue/ {
          proxy_pass http://catalogue:8080/;
        }
      }
    }


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels:
    app: web
    demo: deployment
    env: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      demo: deployment
      env: web
  template:
    metadata:
      labels:
        app: web
        demo: deployment
        env: web
    spec:
      volumes:
      - name: nginx-conf
        configMap:
          name: web #name of configmap
          items:
            - key: nginx.conf
              path: nginx.conf
      containers:
      - name: mongodb
        image: praveen538/web:v1
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-conf 
            subPath: nginx.conf #name of configmap
            readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    app: web
    demo: deployment
    env: web
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port
